server:
  port: 8081

spring:
  application:
    name: server-user
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml
  type-aliases-package: com.oddmy.blog.server.user.pojo