server:
  port: 9000
spring:
  application:
    name: server-manage
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka